name: Build and release

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: 'ubuntu:18.04' # start with a clean environment instead of the default github runner for higher reproducibility
    steps:
    - name: update_git
      run: add-apt-repository ppa:git-core/ppa
    - name: preinstall
      run: apt update && apt -y install sudo wget rsync g++ make cmake git
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/ubuntu64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build
# Skip tests for now
#    - name: test
#      run: cd ../my_build/quandenser && sudo make install && make test ARGS="-V"
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: ubuntu-packages
        path: ../my_rel

  build-fedora:
    runs-on: ubuntu-latest
    container: 'fedora:35'
    steps:
    - name: preinstall
      run: dnf install -y wget rsync make git
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/fedora64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: fedora-packages
        path: ../my_rel

  build-centos:
    runs-on: ubuntu-latest
    container: 'centos:centos7'
    steps:
    - name: update_git
      run: yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
    - name: preinstall
      run: yum check-update && yum install -y sudo scl-utils wget make git
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/centos64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: centos-packages
        path: ../my_rel

  build-tarball:
    runs-on: ubuntu-latest
    container: 'ubuntu:18.04' # start with a clean environment instead of the default github runner for higher reproducibility
    steps:
    - name: update_git
      run: add-apt-repository ppa:git-core/ppa
    - name: preinstall
      run: apt update && apt -y install sudo wget rsync g++ make cmake git
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: ./admin/builders/tarball64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: tarball-packages
        path: ../my_rel

  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: mkdir -p ../my_rel ../my_build
    - name: configure_and_make
      run: admin/builders/osx64_build.sh -s `pwd`/.. -r `pwd`/../my_rel -b `pwd`/../my_build
# Skip tests for now
#    - name: test
#      run: cd ${HOME}/my_build/quandenser && sudo make install && make test ARGS="-V"
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: osx-packages
        path: ../my_rel

  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: create_dirs
      run: CD .. || MKDIR my_rel my_build
    - name: configure_and_make
      run: |
        CD ..
        SET base_dir=%cd%
        ECHO %base_dir%
        CALL quandenser\admin\builders\nativew64_build.bat -s %base_dir% -r %base_dir%\my_rel -b %base_dir%\my_build
    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: win64-packages
        path: ..\my_rel

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-centos, build-fedora, build-tarball, build-osx, build-win64]
    if: startsWith(github.ref, 'refs/tags/rel-')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - run : |
        ls -R
        mkdir packages
        tar -czvf packages/ubuntu.tar.gz -C ubuntu-packages $(ls ubuntu-packages)
        tar -czvf packages/centos.tar.gz -C centos-packages $(ls centos-packages)
        tar -czvf packages/fedora.tar.gz -C fedora-packages $(ls fedora-packages)
        tar -czvf packages/tarball.tar.gz -C tarball-packages $(ls tarball-packages)
        zip -j -r packages/osx.zip osx-packages/*
        zip -j -r packages/win64.zip win64-packages/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/*
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
